s = set()
n = input ("Enter nmber :")
s.add(int(n))
n = input ("Enter nmber :")
s.add(int(n))
n = input ("Enter nmber :")
s.add(int(n))
n = input ("Enter nmber :")
s.add(int(n))
n = input ("Enter nmber :")
s.add(int(n))
n = input ("Enter nmber :")
s.add(int(n))
n = input ("Enter nmber :")
s.add(int(n))
n = input ("Enter nmber :")
s.add(int(n))

print(s)